#markdown_extensions: 
#  - attr_list
use_directory_urls: false
site_name: CRM Наказ
nav:
  - Быстрый старт:
    - Добавить Обращение: howto/leads/new_lead.md
    - Добавить Компанию: howto/organizations/new_org.md
    - Добавить Контакт: howto/contacts/new_contact.md
    #- Быстрое меню Создать: howto/others/fast_create.md
    #- Изменить информацию о Компании: howto/organizations/edit_org.md
    #- Изменить Контакт: howto/contacts/edit_contact.md
    - Внесение изменений: howto/others/edit.md
    - Фильтр и сортировка: howto/others/filtering.md
    - Быстрый поиск: howto/others/fast_search.md
    - Создать отчет в Эксель: howto/others/export_xlsx.md

    # - Внести изменения в Cделку: howto/leads/edit_lead.md
    # - Авторизация Сделки: howto/leads/authorize_lead.md
    # - Отчет по Сделке: howto/leads/report_lead.md
    # - Управление списком Сделок: howto/leads/filter_leads.md
    # - Закрытие Сделки: howto/leads/close_deal.md
    # - Отчет по Компании: howto/organizations/report_org.md
    # - Управление списком Компаний: howto/organizations/filter_orgs.md
    # - Заполнить Спецификацию к Сделке: howto/specs/new_spec.md
    # - Изменить Спецификацию в Сделке: howto/specs/edit_spec.md
    # - Сообщить об ошибке: howto/others/report_err.md
    #- Добавить новый Товар: howto/products/new_product.md
  #- Руководство Пользователя:
    #- Пользовательский интерфейс:
    #  - Главное окно: users_guide/ui/lorem.md
    #- Сделки:
    #  - Информация о сделке: users_guide/leads/lorem.md
    #- Компании: users_guide/organizations/lorem.md
    #- Контакты: users_guide/contacts/lorem.md
  #- Руководство администратора: admin_guide/lorem.md

theme: 
  name: material
